// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd94w8uF5nnFpiS81oENXPYxl5bFBcbsU',
    appId: '1:131818180841:android:9d0569246ad6b8e3806078',
    messagingSenderId: '131818180841',
    projectId: 'fchat-96803',
    storageBucket: 'fchat-96803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqFKFe88GzGn4C3qToU-YAPn3YQKMW1T8',
    appId: '1:131818180841:ios:4fb3ea4d150a47e2806078',
    messagingSenderId: '131818180841',
    projectId: 'fchat-96803',
    storageBucket: 'fchat-96803.appspot.com',
    androidClientId: '131818180841-lv1ln41rfjm4nrot7ehfttv3vpcptqev.apps.googleusercontent.com',
    iosClientId: '131818180841-pos4sv06kcpfmpjs78q2pu33r44c76r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fChat',
  );
}
